# Generated by Django 5.1.5 on 2025-01-31 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indigital', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='horario',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
