# Generated by Django 5.1.5 on 2025-02-04 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indigital', '0002_reserva_horario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='laboratorio',
        ),
        migrations.AddField(
            model_name='reserva',
            name='numLaboratorio',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='data',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Laboratorio',
        ),
    ]
