# Generated by Django 5.1.5 on 2025-02-04 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indigital', '0003_remove_reserva_laboratorio_reserva_numlaboratorio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laboratorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numLaboratorio', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='numLaboratorio',
        ),
        migrations.AddField(
            model_name='reserva',
            name='laboratorio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='indigital.laboratorio'),
        ),
    ]
