# Generated by Django 5.1.5 on 2025-02-05 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indigital', '0004_laboratorio_remove_reserva_numlaboratorio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='data',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='horario',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='laboratorio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indigital.laboratorio'),
        ),
    ]
