# Generated by Django 5.1.6 on 2025-02-15 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indigital', '0007_remove_laboratorio_numlaboratorio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboratorio',
            name='num_laboratorio',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='disponibilidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indigital.disponibilidade'),
        ),
    ]
