# Generated by Django 5.1.6 on 2025-02-15 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indigital', '0008_alter_laboratorio_num_laboratorio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='vagas_disponiveis',
            field=models.IntegerField(null=True),
        ),
    ]
