# Generated by Django 5.1.6 on 2025-02-15 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indigital', '0009_reserva_vagas_disponiveis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='vagas_disponiveis',
        ),
    ]
