# Generated by Django 5.1.6 on 2025-02-17 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indigital', '0011_alter_disponibilidade_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='disponibilidade',
            unique_together=set(),
        ),
    ]
