# Generated by Django 5.1.6 on 2025-02-18 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indigital', '0013_alter_disponibilidade_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disponibilidade',
            old_name='horario',
            new_name='horario_fim',
        ),
        migrations.AlterUniqueTogether(
            name='disponibilidade',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='disponibilidade',
            name='horario_inicio',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='disponibilidade',
            unique_together={('laboratorio', 'data', 'horario_inicio', 'horario_fim')},
        ),
    ]
