# Generated by Django 5.1.6 on 2025-07-07 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indigital', '0015_alter_disponibilidade_horario_inicio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laboratorio',
            name='vagas',
        ),
        migrations.AddField(
            model_name='disponibilidade',
            name='vagas',
            field=models.IntegerField(default=30),
        ),
    ]
