# Generated by Django 5.1.6 on 2025-07-10 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indigital', '0017_filaespera'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filaespera',
            options={'ordering': ['data_solicitacao']},
        ),
        migrations.RenameField(
            model_name='filaespera',
            old_name='data_inscricao',
            new_name='data_solicitacao',
        ),
    ]
