# Generated by Django 5.1.6 on 2025-07-21 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indigital', '0018_alter_filaespera_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratorio',
            name='capacidade',
            field=models.IntegerField(default=30),
        ),
    ]
