# Generated by Django 5.1.6 on 2025-07-21 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indigital', '0019_laboratorio_capacidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='vagas',
            field=models.IntegerField(),
        ),
    ]
