# Generated by Django 5.1.6 on 2025-07-22 18:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indigital', '0020_alter_disponibilidade_vagas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='disponibilidade',
            name='monitor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monitor_disponibilidade', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reserva',
            name='status_frequencia',
            field=models.CharField(blank=True, choices=[('P', 'Presente'), ('F', 'Faltou')], default='', max_length=1),
        ),
    ]
