# Generated by Django 5.1.6 on 2025-07-24 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indigital', '0021_disponibilidade_monitor_reserva_status_frequencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='status_frequencia',
            field=models.CharField(blank=True, choices=[('P', 'Presente'), ('F', 'Faltou'), ('N', 'Não registrado')], default='', max_length=1),
        ),
    ]
