# Generated by Django 5.1.6 on 2025-09-25 19:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indigital', '0022_alter_reserva_status_frequencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='data_solicitacao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reserva',
            name='status_aprovacao',
            field=models.CharField(choices=[('P', 'Pendente'), ('A', 'Aprovada'), ('R', 'Rejeitada')], default='P', max_length=1),
        ),
    ]
