# Generated by Django 5.1.6 on 2025-09-25 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indigital', '0023_reserva_data_solicitacao_reserva_status_aprovacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='status_aprovacao',
            field=models.CharField(choices=[('P', 'Pendente'), ('A', 'Aprovada'), ('R', 'Rejeitada')], default='', max_length=1),
        ),
    ]
