# Generated by Django 5.1.6 on 2025-02-13 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_user_matricula_user_serie_user_turno'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='perfil_fotos/'),
        ),
        migrations.AddField(
            model_name='user',
            name='vinculo',
            field=models.CharField(choices=[('admin', 'Administrador'), ('aluno', 'Aluno')], default='aluno', max_length=10),
        ),
    ]
