# Generated by Django 5.1.6 on 2025-02-13 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_user_foto_perfil_user_vinculo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='vinculo',
        ),
    ]
