# Generated by Django 5.1.6 on 2025-08-03 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_remove_user_serie_remove_user_turno_user_perfil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='matricula',
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=20, unique=True, verbose_name='Matrícula'),
        ),
    ]
