# Generated by Django 5.1.6 on 2025-09-26 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_remove_user_matricula_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='suap_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail no SUAP'),
        ),
        migrations.AddField(
            model_name='user',
            name='suap_foto_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL da Foto no SUAP'),
        ),
        migrations.AddField(
            model_name='user',
            name='suap_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='ID SUAP'),
        ),
        migrations.AddField(
            model_name='user',
            name='suap_nome_completo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome completo no SUAP'),
        ),
        migrations.AddField(
            model_name='user',
            name='suap_vinculo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Vínculo no SUAP'),
        ),
    ]
