# Generated by Django 5.1.6 on 2025-10-14 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_alter_user_email_alter_user_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Usuário', 'verbose_name_plural': 'Usuários'},
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
