# Generated by Django 5.1.6 on 2025-10-14 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_alter_user_options_alter_user_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='perfil',
            field=models.CharField(choices=[('aluno', 'Aluno'), ('administrador', 'Administrador'), ('monitor', 'Monitor'), ('outro', 'Outro')], default='aluno', max_length=20),
        ),
    ]
